os: linux
dist: bionic
language: python

cache:
  directories:
    - $HOME/.cache/pip

python:
  - 3.6
  - 3.7
  - 3.8

env:
    global:
        - CHECK_TYPE="test"
        - INSTALL_DEPENDS="pip setuptools"

matrix:
    include:
        - python: 3.6
          env: CHECK_TYPE="style"

before_install:
  - python -m pip install --upgrade virtualenv
  - python -m virtualenv --python=python /tmp/venv
  - source /tmp/venv/bin/activate
  - which python
  - python --version
  - python -m pip --version
  - python -m pip install --upgrade $INSTALL_DEPENDS
  - python -m pip --version

install:
  - travis_retry python -m pip install .
  - |
    INTENDED_VERSION="$(python -c 'import versioneer; print(versioneer.get_version())')"
    pushd /tmp
    INSTALLED_VERSION="$(python -c 'import smriprep; print(smriprep.__version__)')"
    python -c 'import smriprep; print(smriprep.__file__)'
    echo "Intended: $INTENDED_VERSION"
    echo "Installed: $INSTALLED_VERSION"
    test "$INTENDED_VERSION" == "$INSTALLED_VERSION"
    popd

before_script:
  - travis_retry python -m pip install .[$CHECK_TYPE]

script:
  - |
    if [ "$CHECK_TYPE" == "style" ]; then
      flake8 smriprep
    elif [ "$CHECK_TYPE" == "test" ]; then
      pytest -v --cov smriprep --cov-report xml:cov.xml smriprep
    else
      false
    fi

after_script:
  - python -m pip install codecov
  - codecov
