name: base
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - asn1crypto=0.24.0=py37_0
  - blas=1.0=mkl
  - ca-certificates=2021.7.5=h06a4308_1
  - cairo=1.14.12=h8948797_3
  - certifi=2021.5.30=py37h06a4308_0
  - cffi=1.11.5=py37he75722e_1
  - chardet=3.0.4=py37_1
  - conda=4.5.11=py37_0
  - conda-env=2.6.0=1
  - cryptography=3.3.2=py37h3c74f83_0
  - cycler=0.10.0=py37_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.4.1=h2531618_2
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.4=h5ab3b9f_0
  - fribidi=1.0.10=h7b6447c_0
  - glib=2.63.1=h5a9c865_0
  - graphite2=1.3.14=h23475e2_0
  - graphviz=2.40.1=h21bd128_2
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - harfbuzz=1.8.8=hffaf4a1_0
  - icu=58.2=he6710b0_3
  - idna=2.7=py37_0
  - intel-openmp=2019.4=243
  - jpeg=9d=h7f8727e_0
  - kiwisolver=1.3.1=py37h2531618_0
  - libedit=3.1.20210714=h7f8727e_0
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.2.0=h85742a9_0
  - libuuid=1.0.3=h1bed415_2
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.8=h26e45fe_1
  - libxslt=1.1.32=h1312cb7_0
  - lz4-c=1.9.3=h295c915_1
  - matplotlib=2.2.2=py37hb69df0a_2
  - mkl=2018.0.3=1
  - mkl-service=1.1.2=py37h90e4bf4_5
  - mkl_fft=1.0.6=py37h7dd41cf_0
  - mkl_random=1.0.1=py37h4414c95_1
  - ncurses=6.2=he6710b0_1
  - numpy=1.15.4=py37h1d66e8a_0
  - numpy-base=1.15.4=py37h81de0dd_0
  - openssl=1.1.1q=h7f8727e_0
  - pandas=0.23.4=py37h04863e7_0
  - pango=1.42.4=h049681c_0
  - pcre=8.45=h295c915_0
  - pip=19.1.1=py37_0
  - pixman=0.40.0=h7f8727e_1
  - pycosat=0.6.3=py37h14c3975_0
  - pycparser=2.18=py37_1
  - pyopenssl=18.0.0=py37_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py37h05f1152_2
  - pysocks=1.6.8=py37_0
  - python=3.7.1=h0371630_7
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytz=2021.1=pyhd3eb1b0_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - requests=2.19.1=py37_0
  - ruamel_yaml=0.15.46=py37h14c3975_0
  - scikit-learn=0.19.1=py37hedc7406_0
  - scipy=1.1.0=py37hfa4b5c9_1
  - setuptools=58.0.4=py37h06a4308_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.33.0=h62c20be_0
  - tbb=2021.3.0=hd09550d_0
  - tbb4py=2021.3.0=py37hd09550d_0
  - tk=8.6.11=h1ccaba5_0
  - tornado=6.1=py37h27cfd23_0
  - traits=4.6.0=py37h7b6447c_3
  - urllib3=1.23=py37_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - yaml=0.1.7=had09818_2
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - alabaster==0.7.12
    - annexremote==1.5.0
    - appdirs==1.4.4
    - attrs==21.2.0
    - babel==2.9.1
    - bids-validator==1.8.4
    - bleach==4.1.0
    - boto==2.49.0
    - cached-property==1.5.2
    - ci-info==0.2.0
    - citeproc-py==0.6.0
    - click==8.0.3
    - coverage==6.0.2
    - cython==0.29.24
    - datalad==0.15.2
    - decorator==4.4.2
    - defusedxml==0.7.1
    - deprecated==1.2.13
    - docopt==0.6.2
    - docutils==0.17.1
    - duecredit==0.9.1
    - entrypoints==0.3
    - etelemetry==0.2.2
    - fasteners==0.16.3
    - filelock==3.3.1
    - future==0.18.2
    - fuzzywuzzy==0.18.0
    - h5py==3.5.0
    - humanize==3.12.0
    - imageio==2.10.1
    - imagesize==1.2.0
    - importlib-metadata==4.8.1
    - indexed-gzip==1.6.4
    - iniconfig==1.1.1
    - ipython-genutils==0.2.0
    - iso8601==0.1.16
    - isodate==0.6.0
    - jeepney==0.7.1
    - jinja2==3.0.2
    - joblib==1.1.0
    - jsonschema==4.1.2
    - jupyter-client==7.0.6
    - jupyter-core==4.9.1
    - jupyterlab-pygments==0.1.2
    - keyring==23.2.1
    - keyrings-alt==4.1.0
    - lockfile==0.12.2
    - lxml==4.6.3
    - markupsafe==2.0.1
    - mistune==0.8.4
    - msgpack==1.0.2
    - nbclient==0.5.4
    - nbconvert==6.2.0
    - nbformat==5.1.3
    - nbsphinx==0.8.7
    - nest-asyncio==1.5.1
    - networkx==2.5.1
    - nibabel==3.2.1
    - niflow-nipype1-workflows==0.0.5
    - nilearn==0.6.2
    - nipype==1.7.1
    - nitime==0.9
    - nitransforms==20.0.0rc5
    - num2words==0.5.10
    - packaging==21.0
    - pandocfilters==1.5.0
    - patool==1.12
    - patsy==0.5.2
    - pillow==8.4.0
    - pluggy==1.0.0
    - pockets==0.9.1
    - prov==2.0.0
    - psutil==5.8.0
    - py==1.10.0
    - pybids==0.13.2
    - pydot==1.4.2
    - pydotplus==2.0.2
    - pygithub==1.55
    - pygments==2.10.0
    - pyjwt==2.3.0
    - pynacl==1.4.0
    - pyrsistent==0.18.0
    - pytest==6.2.5
    - pytest-env==0.6.2
    - python-gitlab==2.10.1
    - python-levenshtein==0.12.2
    - pywavelets==1.1.1
    - pyyaml==6.0
    - pyzmq==22.3.0
    - rdflib==6.0.2
    - requests-toolbelt==0.9.1
    - scikit-image==0.17.2
    - seaborn==0.11.2
    - secretstorage==3.3.1
    - sentry-sdk==1.4.3
    - simplejson==3.17.5
    - sklearn==0.0
    - snowballstemmer==2.1.0
    - sphinx==4.2.0
    - sphinx-argparse==0.3.1
    - sphinx-rtd-theme==0.4.3
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-napoleon==0.7
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - sqlalchemy==1.3.24
    - svgutils==0.3.1
    - tedana==0.0.9a1
    - templateflow==0.7.1
    - testpath==0.5.0
    - threadpoolctl==3.0.0
    - tifffile==2021.10.12
    - toml==0.10.2
    - tqdm==4.62.3
    - traitlets==5.1.1
    - transforms3d==0.3.1
    - typing-extensions==3.10.0.2
    - webencodings==0.5.1
    - whoosh==2.7.4
    - wrapt==1.13.2
    - zipp==3.6.0
prefix: /usr/local/miniconda
