name: Docker build

on:
  workflow_dispatch:
  push:
    branches: [ "master", "main", "maint/*", "gha-docker*" ]
    tags: "*"
  pull_request:
    branches: [ "master", "main", "maint/*" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  FORCE_COLOR: true

jobs:
  build-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v5
        with:
          fetch-depth: 200
          fetch-tags: true
          ref: ${{ github.ref }}
          persist-credentials: false

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3
        with:
          driver: docker

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get base image tag, check
        id: base
        run: |
          export BASE_IMAGE=$( grep BASE_IMAGE= Dockerfile | cut -d= -f2 )
          export BASE_IMAGE_NAME=${BASE_IMAGE%:*}
          export BASE_TAG=${BASE_IMAGE#*:}
          echo "image=$BASE_IMAGE" >> $GITHUB_OUTPUT
          echo "name=$BASE_IMAGE_NAME" >> $GITHUB_OUTPUT
          echo "tag=$BASE_TAG" >> $GITHUB_OUTPUT
          env
          if docker manifest inspect $BASE_IMAGE; then
            echo "build=false" >> $GITHUB_OUTPUT
          else
            echo "build=true" >> $GITHUB_OUTPUT
          fi

      - name: Build base image
        if: steps.base.outputs.build == 'true'
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          file: Dockerfile.base
          load: true
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.base.outputs.image }}
            ${{ steps.base.outputs.name }}:latest
          platforms: linux/amd64
          cache-from: |
            type=registry,ref=${{ steps.base.outputs.name }}:latest
          cache-to: type=inline

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          cache-from: |
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:gha-docker
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TARGET_BRANCH }}
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tags[0] }}
          cache-to: type=inline
        env:
          TARGET_BRANCH: ${{ github.base_ref || github.ref_name }}
